language: scala
scala:
  - 2.11.5
  - 2.10.4
jdk:
  - oraclejdk7
notifications:
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/20b8e51c61363eee95e8
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: false     # default: false
  email:
    - truffaut.julien@gmail.com
script: sbt ++$TRAVIS_SCALA_VERSION test
